### ISSUE TITLE
[Feature Request] No Loot mode

### ISSUE THREAD

**Issue by notheowner** [Maurits825/herbi-afk#11]
The dynamic swap of menus is really nice, but it doesn't work that well when you are not looting herbi.
A no looting mode which doesn't draw a line to loot herbi and adjusts menu swaps accordingly would be perfect if possible.

**Comment by Maurits825** [comment]
implemented with 27719ed, can close when [hub pr](https://github.com/runelite/plugin-hub/pull/5981) is merged

**Comment by notheowner** [comment]
![image](https://github.com/Maurits825/herbi-afk/assets/86596679/c0d0275b-c081-4e50-9e33-dd3494daf645)
Awesome, thank you!
