### ISSUE TITLE
trail objects

### ISSUE THREAD

**Issue by pettrs** [Maurits825/herbi-afk#2]
Currently both trail objects are marked in a path with the normal herbiboar plugin. please add a seperate trail object only marking the correct trail object so that the option can be disabled in the normal plugin. Perferrably with the clickboxes option aswell aswell.

**Comment by pettrs** [comment]
possiblt also a stats bar to encourage higher efficiency? e.g catches per hours, fastest complete trail, ticks lost, herblore loot tracker (in gp) or gp/h?, etc..

**Comment by Maurits825** [comment]
the core plugin was updated to only highlight the correct trail. made a sperate issue for the other comment
