### ISSUE TITLE
Track reset

### ISSUE THREAD

**Issue by pettrs** [Maurits825/herbi-afk#3]
The track should reset after herbiboar leads you in a clircle

Currently, when you lost track of herbbiboar; 
(The creature has successfully confused you with its tracks, leading you round in circles.)
The track continues marking the old path. here it should reset to a new start object

here it shows path to an old trail object after i was lead in circles
![image](https://user-images.githubusercontent.com/75093127/143201297-7ec3dd54-deb9-434e-b62d-b97860094608.png)

**Comment by Maurits825** [comment]
Fixed with fa1ffcdd105e603175f47f0c40b14964ed7a809f
