### ISSUE TITLE
Disable pathline when inactive

### ISSUE THREAD

**Issue by pettrs** [Maurits825/herbi-afk#5]
When doing other content on fossil island, or just passing through, the pathline can be quite annoing,a nd obstructive. possibly disable it when you're not actively doing herbiboar? so that the first time you start doing herbiboar upon arrival, you ahve to locate the first tunnel yourself before it starts? possibly add a feature that makes it so the line is only enables when you ahve magic secatures equipped. because hwo in their right mind does herbiboar wihtout a magic secature? then jsut have a chekcbox in the settings that allow oyu to enable the line regardless of secatures being equipped if someone were to do it without

**Comment by Maurits825** [comment]
With 27204ab553d05ef3ed54d4d56fc1f54d0dd3dc28 the path line only show after you search a start spot. The line will then stay until you either log out/hop worlds or tp/move out the herbi area.
